package com.solutionsmax.gurukoolmax_v3.core.common

object MasterTableNames {
    const val MASTERS_FLEET_FUEL_TYPES = "MASTERS_FLEET_FUEL_TYPES"
    const val MASTERS_CONFIGURATION_CALENDAR_YEAR = "MASTERS_CONFIGURATION_CALENDAR_YEAR"
    const val MASTERS_FLEET_MANAGEMENT_SERVICE_TYPES = "MASTERS_FLEET_MANAGEMENT_SERVICE_TYPES"
    const val MASTERS_FLEET_MANAGEMENT_ASSIGNMENT_TYPE = "MASTERS_FLEET_MANAGEMENT_ASSIGNMENT_TYPE"
    const val MASTERS_FLEET_MANAGEMENT_DOCUMENTS = "MASTERS_FLEET_MANAGEMENT_DOCUMENTS"
    const val MASTERS_FLEET_MANAGEMENT_INSURANCE_POLICY_PERIOD =
        "MASTERS_FLEET_MANAGEMENT_INSURANCE_POLICY_PERIOD"
    const val MASTERS_FLEET_MANAGEMENT_VEHICLE_MAINTENANCE_LIST =
        "MASTERS_FLEET_MANAGEMENT_VEHICLE_MAINTENANCE_LIST"
    const val MASTERS_FLEET_MANAGEMENT_VEHICLE_MAKER = "MASTERS_FLEET_MANAGEMENT_VEHICLE_MAKER"
    const val MASTERS_FLEET_MANAGEMENT_VEHICLE_MODEL = "MASTERS_FLEET_MANAGEMENT_VEHICLE_MODEL"
    const val MASTERS_FLEET_MANAGEMENT_VEHICLE_REPAIR_LIST =
        "MASTERS_FLEET_MANAGEMENT_VEHICLE_REPAIR_LIST"
    const val MASTERS_TIMETABLE_TIME_RANGE_HR = "MASTERS_TIMETABLE_TIME_RANGE_HR"
    const val MASTERS_TIMETABLE_TIME_RANGE_MM = "MASTERS_TIMETABLE_TIME_RANGE_MM"
    const val MASTERS_TIMETABLE_TIME_CYCLE = "MASTERS_TIMETABLE_TIME_CYCLE"
    const val MASTERS_ACADEMICS_EDUCATIONAL_BOARD = "ACADEMICS_AFFILIATION_REGISTRATION"
    const val MASTERS_KNOWLEDGE_MANAGEMENT_CONTENT_TYPES =
        "MASTERS_KNOWLEDGE_MANAGEMENT_CONTENT_TYPES"
    const val MASTERS_KNOWLEDGE_MANAGEMENT_SOURCES = "MASTERS_KNOWLEDGE_MANAGEMENT_SOURCES"
    const val MASTERS_KNOWLEDGE_MANAGEMENT_FORMAT_TYPES =
        "MASTERS_KNOWLEDGE_MANAGEMENT_FORMAT_TYPES"
    const val MASTERS_ENQUIRY_CALENDAR_YEAR = "MASTERS_ENQUIRY_CALENDAR_YEAR"
    const val MASTERS_ACADEMICS_ASSIGNMENT_CATEGORIES = "MASTERS_ACADEMICS_ASSIGNMENT_CATEGORIES"
    const val MASTERS_PROJECTS_REPOSITORY_WORKFLOW_STATUS =
        "MASTERS_PROJECTS_REPOSITORY_WORKFLOW_STATUS"
}